spring:
  application:
    name: furia-fan-bot
  deserialization:
    ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:my-password}
      username: ${REDIS_USERNAME:default}

telegram:
  creator:
    id: ${TELEGRAM_CREATOR_ID}
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

panda_score:
  api:
    url: ${PANDA_SCORE_API_URL}
    token: ${PANDA_SCORE_API_TOKEN}